# InternVL3_5 configuration for event to FSL conversion

# Required paths
# input_dir: /configure-via-CLI
# output_dir: /configure-via-CLI

# EventToFSL configuration
event_to_fsl_config:
  # Model configuration
  tokenizer_name: "OpenGVLab/InternVL3_5-1B-HF"

  # Tokenization configuration (optional). Defaults are auto-detected from tokenizer_name
  encoder_type: "factorized"  # Options: "hierarchical", "factorized"
  # image_token_config:
  #   prefix: "<img>"
  #   token: "<IMG_CONTEXT>"
  #   length: 256
  #   suffix: "</img>"

  # FSL dataset configuration
  fsl_dataset:
    pad_token_id: 0 # overrided from tokenizer automatically
    max_sequence_length: 4096
    include_samples_without_images: False
    action_topics: ["keyboard", "mouse/raw"]  # Topics to apply time shift and skip logic to
    skip_first_t_seconds_for_action: null
    time_shift_seconds_for_action: null

  # Processing options
  num_proc: 32
  fsl_workers: 4
